# Generate HTML for service publications using this yaml file
# 
# A service block follows this format:
#
# - title: [Title of the service, including position]
#   location: [OPTIONAL: Place where service occurred, including city and state if possible]
#   date: [OPTIONAL: dates of which the service occurred]
#   desc: [Any additional description describing your work]
#   year: [Year that the service was done]
#   links:
#     - type: Type of media that you are linking (Will be placeholder for the link)
#       url: Url to the media
#     - type:
#       url:
#     (etc.)
#
# If there is anything else you would want added onto this file, notify the owner of this webpage

service:
  
  # 2022 -----------------------------------

  - title: "NIH Special Emphasis Panel: Imaging, Surgery and Bioengineering; NSF Panel"
    year: 2022
    
  - title: ECCV 2022 Best Paper Award Committee Member
    year: 2022
    links:
      - type: Website
        url: https://eccv2022.ecva.net/organizers/

  - title: CVPR 2022 Paper Award Committee Member
    year: 2022
    links:
      - type: Website
        url: https://cvpr2022.thecvf.com/cvpr-2022-paper-awards

  - title: Area-Chair for Computer Vision and Pattern Recognition (CVPR) 2022
    year: 2022

  - title: Area-Chair for The European Conference on Computer Vision (ECCV) 2022
    year: 2022
    
  # 2021 -----------------------------------

  - title: Area-Chair for International Conference of Computer Vision (ICCV) 2021
    year: 2021

  - title: Area-Chair for Computer Vision and Pattern Recognition (CVPR) 2021
    year: 2021

  # 2019 -----------------------------------

  - title: Dancing With Robots (DwR) - Co-Organizer
    location: Penn State University, University Park, PA
    date: "7/29 - 8/2"
    desc: Computer Science and Engineering Summer Camp (DwR-CSE)
    year: 2019
    links:
      - type: Website
        url: https://sites.psu.edu/dancingwithrobots/
      - type: Women in AI Panelists
        url: https://sites.psu.edu/dancingwithrobots/women-in-ai/

  - title: Area-Chair for Computer Vision and Pattern Recognition (CVPR) 2019
    location: Long Beach, CA
    date: June 2019
    year: 2019
    links:
      - type: Website
        url: http://cvpr2019.thecvf.com/

  - title: Program Co-Chair for WACV
    location: Waikoloa, HI
    date: January 2019
    year: 2019
    links:
      - type: Website
        url: http://wacv19.uccs.us/people/

  - title: Keynote Speaker for Computational and Mathematical Models in Vision (MODVIS 2019)
    year: 2019
    links:
      - type: Keynote Info
        url: https://www.conf.purdue.edu/modvis/keynote.aspx
      - type: Conference Website
        url: https://www.conf.purdue.edu/modvis/default.aspx

  # 2018 -----------------------------------

  - title: Area-Chair for ACCV 2018
    location: Perth Western, Australia
    date: December 2018
    year: 2018
    links:
      - type: Website
        url: http://accv2018.net/

  - title: NIH/NIBIB P41 Site Visit
    date: June 2018
    year: 2018

  - title: NIH Special Emphasis Panel (RPHB)
    date: March 2018
    year: 2018

  # 2017 -----------------------------------

  - title: Program Chair for CVF/IEEE, Computer Vision and Pattern Recognition Conference (CVPR)
    year: 2017
    links:
      - type: Website
        url: http://cvpr2017.thecvf.com/organizers

  - title: "Co-Chair ICCV 2017 Challenge: Detecting Symmetry in the Wild"
    year: 2017
    links:
      - type: ICCV Website
        url: http://iccv2017.thecvf.com/
      - type: Challenge Website
        url: https://sites.google.com/view/symcomp17

  - title: Associate Editor for IEEE TRANSACTION of PATTERN ANALYSIS and MACHINE INTELLIGENCE (PAMI)
    year: 2017

  # 2016 -----------------------------------

  - title: Co-Program Chair for CVPR 2017
    year: 2016

  - title: IEEE PAMI Associate Editor
    year: 2016

  - title: CVIU (ELSEVIER) Area Editor
    year: 2016

  - title: NIH Biodata Management and Analysis (BDMA) Study Section
    year: 2016

  - title: NIH SBIR/STTR Health Informatics Review Panel
    year: 2016

  - title: NSF Grant Review Panel(s)
    year: 2016

  # 2015 -----------------------------------

  - title: IEEE PAMI Associate Editor
    year: 2015

  - title: CVIU Editorial Board Member
    year: 2015

  - title: NIH Biodata Management and Analysis (BDMA) Panelist
    year: 2015

  - title: NIH P41 Site Visit
    year: 2015

  - title: NSF Grant Review Panel(s)
    year: 2015

  # 2014 -----------------------------------

  - title: Associate Editor for IEEE Transaction on Pattern Analysis and Machine Intelligence (PAMI)
    year: 2014

  - title: Area Editor for Computer Vision and Image Understanding Journal (CVIU)
    year: 2014
    links:
      - type: Website
        url: http://www.cv-foundation.org/CVPR2014/CVPR2017-Proposal.pdf

  - title: "Winning bid for Computer Vision and Pattern Recognition Conference 2017 (role: PC)"
    year: 2014

  - title: NIH Panel on BD2K Centers of Excellence for Big Data Computing in the Biomedical Sciences
    date: April 2014
    year: 2014

  - title: Association for Women in Math
    year: 2014

  - title: Invited speaker at JMM
    date: January 18, 2014
    desc: Computational Symmetry for Automated Pattern Discovery
    year: 2014
    links:
      - type: Website
        url: http://jointmathematicsmeetings.org/meetings/national/jmm2014/2160_program.html

  # 2013 ----------------------------------- 

  - title: Chair for CVPR 2013 Workshop
    desc: 2nd International Competition on Symmetry Detection from Real World Images
    year: 2013
    links:
      - type: Website
        url: https://sites.psu.edu/eecslpac/cvpr-2013-workshop/

  - title: Chair and Co-Organizer for Taiji and Advanced Technology for Smart Health Symposium
    date: April 25-27
    year: 2013
    links:
      - type: Website
        url: http://vision.cse.psu.edu/taiji.htm
        type: Flyer
        url: assets/images/taiji_flyer.pdf

  # 2012 ----------------------------------- 

  - title: PI and Director for Vision, Learning, and Pattern Recognition Summer School in Shanghai
    desc: VLPR 2012
    year: 2012
    links:
      - type: Website
        url: http://vision.cse.psu.edu/vlpr2012/vlpr2012.html

  - title: Workshop Chair for the 11th Asian Conference on Computer Vision
    desc: ACCV 2012
    year: 2012
    links:
      - type: Website
        url: hhttp://www.accv2012.org/